spring:
    # rabbitmq
  redis:
    database: 2
    host: 123.207.27.144
    port: 6379
    password:       # 密码（默认为空）
    timeout: 15000  # 连接超时时长（毫秒）
    pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接
    ws-topic-name: myShopingMarket_config #websocket推送redis主题的名称
