server:
  port: 8270
  context-path: /

spring:
  application:
    name: shopping-admin
  # 区分环境：开发环境dev
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:8000/eureka/

# shiro 不拦截路径
shiro:
  anon:
    path:
    # spring cloud 健康检查
    - /login