server:
  port: 8082
spring:
  profiles:
    active: dev
  #thymeleaf模板配置
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
  resources:
    chain:
      strategy:
        content:
          paths: /**
          enabled: true
#加载mybatis文件xml
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    com:
      tiku:
        dao: debug
